/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hong_rise_JniDemoActivity */

#ifndef _Included_com_hong_rise_JniDemoActivity
#define _Included_com_hong_rise_JniDemoActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hong_rise_JniDemoActivity
 * Method:    getCurrentPressure
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hong_rise_JniDemoActivity_getCurrentPressure
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
